export const FETCH_VIDEO_ID = "FETCH_VIDEO_ID";
export const UPDATE_START_MINUTES = "UPDATE_START_MINUTES";
export const UPDATE_START_SECONDS = "UPDATE_START_SECONDS";
export const UPDATE_END_MINUTES = "UPDATE_END_MINUTES";
export const UPDATE_END_SECONDS = "UPDATE_END_SECONDS";